//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleetmanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call_T
    {
        public int CallID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> FMUserID { get; set; }
        public Nullable<bool> JobCardGenerated { get; set; }
        public Nullable<System.DateTime> ReportedOn { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<bool> ExternalGarage { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Note { get; set; }
    }
}
