//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleetmanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMUser_T
    {
        public int FMUserID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Email { get; set; }
        public string FMPassword { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DivisionID { get; set; }
    }
}
