//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleetmanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelConsumption_T
    {
        public int FuelConsumptionID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> Odometer { get; set; }
        public Nullable<int> FuelTypeID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> FillingDate { get; set; }
    }
}
