//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleetmanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCard_T
    {
        public int JobCardID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> CallID { get; set; }
        public Nullable<System.DateTime> JobStarted { get; set; }
        public Nullable<System.DateTime> JobEnded { get; set; }
        public Nullable<int> LabourHours { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    }
}
