//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleetmanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpareServiceDetails_T
    {
        public int SpareServiceDetailsID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> JobCardID { get; set; }
        public Nullable<bool> SparePart { get; set; }
        public Nullable<int> SparePartID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> LabourHour { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
