//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleetmanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_T
    {
        public int VehicleID { get; set; }
        public Nullable<int> FleetCompanyID { get; set; }
        public string VehicleNoName { get; set; }
        public Nullable<int> VehicleNo { get; set; }
        public Nullable<int> VehicleGroupID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> AutoBrandID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public Nullable<decimal> SoldAmount { get; set; }
        public Nullable<int> Life { get; set; }
        public string Color { get; set; }
        public Nullable<int> ServiceFrequency { get; set; }
        public Nullable<int> FuelTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string GPSURL { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    }
}
